### PR TITLE
Microverse Milestone 1: Add initial files

### PR DESCRIPTION
**Pull request by masangana**
In this milestone we:

- Modified README template
- Added index.html
- Added style.css
- Added test.md
- Added linters
- Added .gitignore

### CODE REVIEW

**Review by Donard97 — COMMENTED** [review]
## Hi @masangana , 👋  

_You did a good job so far! 👏 💯_ 

**There are some issues that you still need to work on to go to the next project but you are almost there!** 💪 

133678845-1b015b27-e9bc-4784-a316-bc699db8237a

## Highlights ✅ 

✔️ There is no linter error
✔️ Structure is professional
✔️ Readme file is professional

## Required Changes ♻️

- [ ] Good job on adding title and description of PR but kindly change them and tell us shortly what you did in this branch. Keep shining 💪 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by masangana** [comment]
### @Donard97  
Thanks for your feedback. Please can you check now my changes

**Comment by Donard97** [comment]
> ### @Donard97
> Thanks for your feedback. Please can you check now my changes

Good job now submit it again! 💪

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @masangana👋, 

Great work on making the changes 👏 👏 
You've done well implementing some of the requested changes requested by the previous review, but there are still some which aren't addressed yet.


# Suggested changes
- [ ] **Required:** Great job so far! Kindly share the progress made.
_Check the comments under the review._




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by masangana** [comment]
### @brytebee 
Hello, i didn't understand what i should now. Can you explain me with more details?

**Comment by masangana** [comment]
### @Donard97 , @brytebee 
Hey! can you please check this again before that i request for another Review?
This my last review

**Comment by Donard97** [comment]
> 
> 
> ### @Donard97 , @brytebee 
> 
> Hey! can you please check this again before that i request for another Review?
> 
> This my last review 

@masangana hello, I texted you on slack

**Review by Donard97 — COMMENTED** [review]
## Hi @masangana , 👋  

_Well done on changing the title and description of PR! 💯 👏_ 

**Your project is complete!  There is nothing else to say other than... it's time to merge it** 💪 

## Congratulations! 🎉 🎉 🎉 

giphy (13)

Cheers and Happy coding!👏👏👏

****NOTE**: As I mentioned on Slack please do not merge before getting approved.**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
